package com.onps.pojos;
// Generated Aug 3, 2014 11:14:04 PM by Hibernate Tools 3.6.0



/**
 * Candidate generated by hbm2java
 */
public class Candidate  implements java.io.Serializable {


     private Integer id;
     private String cid;
     private String fname;
     private String lname;
     private String fathersname;
     private String sex;
     private Integer age;
     private String email;
     private String address;
     private String cstate;
     private String city;
     private Integer pincode;
     private byte[] photo;
     private String password;
     private Long phoneno;
     private Integer constituency;
     private String party;
     private Character approved;
     private String promises;

    public Candidate() {
    }

    public Candidate(String cid, String fname, String lname, String fathersname, String sex, Integer age, String email, String address, String cstate, String city, Integer pincode, byte[] photo, String password, Long phoneno, Integer constituency, String party, Character approved, String promises) {
       this.cid = cid;
       this.fname = fname;
       this.lname = lname;
       this.fathersname = fathersname;
       this.sex = sex;
       this.age = age;
       this.email = email;
       this.address = address;
       this.cstate = cstate;
       this.city = city;
       this.pincode = pincode;
       this.photo = photo;
       this.password = password;
       this.phoneno = phoneno;
       this.constituency = constituency;
       this.party = party;
       this.approved = approved;
       this.promises = promises;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCid() {
        return this.cid;
    }
    
    public void setCid(String cid) {
        this.cid = cid;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getFathersname() {
        return this.fathersname;
    }
    
    public void setFathersname(String fathersname) {
        this.fathersname = fathersname;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCstate() {
        return this.cstate;
    }
    
    public void setCstate(String cstate) {
        this.cstate = cstate;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Integer getPincode() {
        return this.pincode;
    }
    
    public void setPincode(Integer pincode) {
        this.pincode = pincode;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Long getPhoneno() {
        return this.phoneno;
    }
    
    public void setPhoneno(Long phoneno) {
        this.phoneno = phoneno;
    }
    public Integer getConstituency() {
        return this.constituency;
    }
    
    public void setConstituency(Integer constituency) {
        this.constituency = constituency;
    }
    public String getParty() {
        return this.party;
    }
    
    public void setParty(String party) {
        this.party = party;
    }
    public Character getApproved() {
        return this.approved;
    }
    
    public void setApproved(Character approved) {
        this.approved = approved;
    }
    public String getPromises() {
        return this.promises;
    }
    
    public void setPromises(String promises) {
        this.promises = promises;
    }




}


