package com.onps.pojos;
// Generated Aug 3, 2014 11:14:04 PM by Hibernate Tools 3.6.0



/**
 * Voter generated by hbm2java
 */
public class Voter  implements java.io.Serializable {


     private Integer id;
     private String vid;
     private String fname;
     private String lname;
     private String fathersname;
     private String sex;
     private Integer age;
     private String email;
     private String address;
     private String vstate;
     private String city;
     private Integer pincode;
     private String password;
     private byte[] photo;
     private Long phoneno;
     private String hasvoted;
     private String hashpass;
     private Integer constituency;
     private Character approved;

    public Voter() {
    }

    public Voter(String vid, String fname, String lname, String fathersname, String sex, Integer age, String email, String address, String vstate, String city, Integer pincode, String password, byte[] photo, Long phoneno, String hasvoted, String hashpass, Integer constituency, Character approved) {
       this.vid = vid;
       this.fname = fname;
       this.lname = lname;
       this.fathersname = fathersname;
       this.sex = sex;
       this.age = age;
       this.email = email;
       this.address = address;
       this.vstate = vstate;
       this.city = city;
       this.pincode = pincode;
       this.password = password;
       this.photo = photo;
       this.phoneno = phoneno;
       this.hasvoted = hasvoted;
       this.hashpass = hashpass;
       this.constituency = constituency;
       this.approved = approved;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVid() {
        return this.vid;
    }
    
    public void setVid(String vid) {
        this.vid = vid;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getFathersname() {
        return this.fathersname;
    }
    
    public void setFathersname(String fathersname) {
        this.fathersname = fathersname;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getVstate() {
        return this.vstate;
    }
    
    public void setVstate(String vstate) {
        this.vstate = vstate;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Integer getPincode() {
        return this.pincode;
    }
    
    public void setPincode(Integer pincode) {
        this.pincode = pincode;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public Long getPhoneno() {
        return this.phoneno;
    }
    
    public void setPhoneno(Long phoneno) {
        this.phoneno = phoneno;
    }
    public String getHasvoted() {
        return this.hasvoted;
    }
    
    public void setHasvoted(String hasvoted) {
        this.hasvoted = hasvoted;
    }
    public String getHashpass() {
        return this.hashpass;
    }
    
    public void setHashpass(String hashpass) {
        this.hashpass = hashpass;
    }
    public Integer getConstituency() {
        return this.constituency;
    }
    
    public void setConstituency(Integer constituency) {
        this.constituency = constituency;
    }
    public Character getApproved() {
        return this.approved;
    }
    
    public void setApproved(Character approved) {
        this.approved = approved;
    }




}


